name: To deploy static website in S3 bucket for QA

on:
  pull_request:
    branches: 
       - develop

jobs:

 build:
  
   runs-on: ubuntu-latest
   steps:
      
      - uses: actions/checkout@v2
     
      - uses: ruby/setup-ruby@v1
        with:
           ruby-version: 2.6
           bundler-cache: true
      
      - name: "Build Site"
        run: bundle exec jekyll build
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
         aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_QA }}
         aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_QA }}
         aws-region: ${{ secrets.AWS_REGION_QA }}

      - name: Sync output to S3 bucket in blog folder
        run: |
          aws s3 sync ./_site/ s3://${{ secrets.S3_BUCKET_NAME_QA }}/blog --ac1 public-read --delete
